# Generated by Django 5.2.6 on 2025-10-29 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('gestion_cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('APROBADO', 'APROBADO'), ('CANCELADO', 'CANCELADO')], default='BORRADOR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='empresa.empresa')),
            ],
            options={
                'db_table': 'asiento_contable',
                'unique_together': {('numero', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=100)),
                ('debe', models.DecimalField(decimal_places=3, max_digits=10)),
                ('haber', models.DecimalField(decimal_places=3, max_digits=10)),
                ('asiento_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_asiento.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_cuenta.cuenta')),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
    ]
