# Generated by Django 5.2.6 on 2025-10-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userempresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolempresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='roles', to='empresa.userempresa'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='user_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='empresa.userempresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', through='empresa.UserEmpresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userempresa',
            unique_together={('usuario', 'empresa')},
        ),
    ]
