# Generated by Django 5.2.6 on 2025-10-29 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_empresas', models.IntegerField(blank=True, null=True)),
                ('cant_colab', models.IntegerField(blank=True, null=True)),
                ('funcionalidad', models.TextField()),
                ('codigo', models.TextField(unique=True)),
                ('cant_consultas_ia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caracteristica',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodos_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('qr', 'QR')], max_length=50)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=50)),
                ('codigo_pago', models.TextField(blank=True, default='')),
                ('id_transaccion_externa', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('codigo', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_mes', models.IntegerField()),
                ('precio', models.FloatField()),
                ('codigo', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tipo_plan',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('codigo', models.TextField(blank=True, default='')),
                ('dia_restante', models.IntegerField(default=0)),
                ('empresa_disponible', models.IntegerField(blank=True, default=0, null=True)),
                ('colab_disponible', models.IntegerField(blank=True, default=0, null=True)),
                ('consultas_ia_restantes', models.IntegerField(blank=True, default=None, null=True)),
                ('estado', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='suscripciones', to='suscripcion.estado')),
            ],
            options={
                'db_table': 'suscripcion',
            },
        ),
    ]
