# Generated by Django 5.2.6 on 2025-10-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripcion.suscripcion'),
        ),
        migrations.AddField(
            model_name='tipoplan',
            name='caracteristica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_plan', to='suscripcion.caracteristica'),
        ),
        migrations.AddField(
            model_name='tipoplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='suscripcion.plan'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='suscripcion.tipoplan'),
        ),
    ]
