# Generated by Django 5.2.6 on 2025-10-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plantilla_rol',
            },
        ),
        migrations.CreateModel(
            name='PlantillaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.PositiveIntegerField()),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='plantilla.plantillaclase')),
            ],
            options={
                'db_table': 'plantilla_clase',
            },
        ),
        migrations.CreateModel(
            name='PlantillaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveBigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('CERRADO', 'CERRADO')], default='ACTIVO', max_length=10)),
                ('clase_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='plantilla.plantillaclase')),
            ],
            options={
                'db_table': 'plantilla_cuenta',
            },
        ),
    ]
